SOURCE_DIR=	..
SOURCE_BUILD=	$(SOURCE_DIR)/build

## ======================================================================

INSTALL_DIR=	$(libmoduledir)/perl5
INSTALL_FILES= \
	LDAP2Any/Entry.pm \
	LDAP2Any/Mapper/TextFile.pm \
	LDAP2Any/Mapper/Base.pm \
	LDAP2Any/Mapper.pm \
	## EOL

## ======================================================================

include $(SOURCE_BUILD)/Makefile.common

install:: install-files

