SOURCE_DIR=	..
SOURCE_BUILD=	$(SOURCE_DIR)/build

## ======================================================================

INSTALL_DIR=	$(libmoduledir)/mapper
INSTALL_FILES= \
	passwd.pm \
	group.pm \
	## EOL

## ======================================================================

include $(SOURCE_BUILD)/Makefile.common

install:: install-files

